### ISSUE TITLE
Multi-object detection and extraction in longslit spectroscopy

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#13]
Multi objects can be identified but there is no handling for them

**Comment by simontorres** [comment]
There a preliminary implementation of this. Need to run a few tests and probably improve the extraction method in order to avoid contamination or cross-contamination of sources.
The name of the output files for multiple targets will be: __original_filename_1.fits__, __original_filename_2.fits__ ... __original_filename_N.fits__ and for single ones will be simply __original_filename.fits__ also consider the __g__  as prefix.

**Comment by b1quint** [comment]
It would be good to have a performance parameter for object separation. Remember that you will not be able to detect different sources if they are too close. People say that they can not be resolved. That depends on their separation and on the observed seeing. Considering that the spacial fwhm is the seeing, they normally can only be resolved if they are separated by more than a fwhm / 2.

**Comment by simontorres** [comment]
We will simulate data with more than one target and see how the identification works and then do the same for extraction.

**Comment by simontorres** [comment]
This issue is not specific enough and is very old.
See #258
