### ISSUE TITLE
Add Example of use and Data Sample For Running the Pipeline

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#136]
Some of the feed I have received about the pipeline's manual was that there is no example of use nor  sample data for testing.

**Comment by b1quint** [comment]
I suggest creating a new repository to host the example data. This repository can also be used for tests. Keep in mind that reps should not have more than 100 Mb in GitHub.

**Comment by simontorres** [comment]
a tar file on zenodo?

**Comment by simontorres** [comment]
Will ignore this for now.
