### ISSUE TITLE
Rename package name

### ISSUE THREAD

**Issue by b1quint** [soar-telescope/goodman_pipeline#151]
Rename package `pipeline` to `goodman-pipeline`.

**Comment by simontorres** [comment]
This was done on #234
The project and the package were renamed to ``goodman_pipeline`` so, the structure is more or less like this.

```
goodman_pipeline
  goodman_pipeline
    core
    images
    ...
  docs
  README
```

For ``pip`` install the package is called ``goodman-pipeline``.
