### ISSUE TITLE
Should `dcr.par` file be removed?

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#170]
With the implementation of `dcr.par` file generator on #162 the option to use the default dcr.par file has turned "kind-of" obsolete.

The implementation should be as follows.

If no --dcr-par-file is not set the dcr file generator should take priority

if --dcr-par-file is set that should take priority but if the file does not exist dcr file generator should take over.

**Comment by b1quint** [comment]
Completely agree. If the pipeline is generating a `dcr.par` file with the default values, it can be deleted. I believe that the suggested implementation is good!

**Comment by simontorres** [comment]
There is a third option which I will be testing in the following days which include a modification to the file generator implemented in #162 which will allow parsing a dictionary with all the parameters. Something I need to add is some validation that all parameters are parsed or set a default in case any of them is not set. This eventually would allow to parse the dcr parameters through command line when calling `redccd`.

**Comment by simontorres** [comment]
The latests suggested changes have not been implemented, either way, I don't think ``dcr.par`` should be removed.
