### ISSUE TITLE
Imaging data wrongly identified as spectroscopic observations

### ISSUE THREAD

**Issue by dsanmartim** [soar-telescope/goodman_pipeline#320]
I've obtained some imaging data and I was trying to use the redccd pipeline to get the ccd reduction done, but the pipeline is wrongly identifying the data as

**[15:00:19][I]: Detected Spectroscopy Data from Red Camera
[15:00:19][I]: Observing Technique: Spectroscopy**

which is wrong. All data inside the raw_path was observed in imaging mode. Below you can find some relevant information to try to understand the issue.

REDCCD pipeline was run using the following parameters:

$> raw_path="/path_to_night/20191220/GOODMAN/RAW/"
$> red_path="/path_to_night/20191220/GOODMAN/REDCCD/"
$> redccd --raw-path "$raw_path" --red-path "$red_path" --flat-normalize mean

I'm using the Goodman HTS Pipeline v1.3.0.

This is the  redccd log output:

_Failed to import any qt binding
[15:00:16][I]: Starting Goodman HTS Pipeline Log
[15:00:16][I]: Local Time    : 2020-04-12 15:00:16.745594
[15:00:16][I]: Universal Time: 2020-04-12 19:00:16.745744
[15:00:17][I]: Pipeline Version: 1.3.0 (latest)
[15:00:17][I]: Found 158 fits files in /path_to_data/20191220/GOODMAN/RAW.
[15:00:17][I]: Folder for reduced data is empty (good).
[15:00:19][I]: Instrument: Red Camera
**[15:00:19][I]: Detected Spectroscopy Data from Red Camera
[15:00:19][I]: Observing Technique: Spectroscopy**
[15:00:21][I]: Organizing data for this configuration: Gain: 3.78, Noise: 8.99, ROI: Imaging 1x1
[15:00:22][I]: Found valid data, appending to data container list
[15:00:22][W]: Determining trim section. Assuming you have only one kind of data in this folder
[15:00:22][I]: Trim Section: [51:4110,2:3096]
[15:00:22][I]: Overscan regions has been tested for ROI Spectroscopic 1x1, 2x2 and 3x3
[15:00:22][I]: Overscan Region: [6:49,1:3096]
[15:00:22][I]: Creating master bias
[15:01:15][I]: Saving FITS file to master_bias_RED_SP_1x1_R08.99_G03.78.fits
[15:01:15][I]: Created master bias: master_bias_RED_SP_1x1_R08.99_G03.78.fits
[15:01:15][W]: Determining trim section. Assuming you have only one kind of data in this folder
[15:01:15][I]: Trim Section: [51:4110,2:3096]
[15:01:15][I]: Overscan regions has been tested for ROI Spectroscopic 1x1, 2x2 and 3x3
[15:01:15][I]: Overscan Region: [6:49,1:3096]
Traceback (most recent call last):
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/bin/redccd", line 4, in <module>
    __import__('pkg_resources').run_script('goodman-pipeline==1.3.0', 'redccd')
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/goodman_pipeline-1.3.0-py3.6.egg/EGG-INFO/scripts/redccd", line 17, in <module>
    GOODMAN_CCD()
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/goodman_pipeline-1.3.0-py3.6.egg/goodman_pipeline/images/goodman_ccd.py", line 262, in __call__
    process_images()
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/goodman_pipeline-1.3.0-py3.6.egg/goodman_pipeline/images/image_processor.py", line 134, in __call__
    morning_twilight=self.morning_twilight)
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/goodman_pipeline-1.3.0-py3.6.egg/goodman_pipeline/core/core.py", line 2233, in name_master_flats
    wavmode = spectroscopic_mode(header=header)
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/goodman_pipeline-1.3.0-py3.6.egg/goodman_pipeline/core/core.py", line 4072, in __call__
    blocking_filter=blocking_filter)
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/goodman_pipeline-1.3.0-py3.6.egg/goodman_pipeline/core/core.py", line 4118, in get_mode
    cam_ang=camera_targ)
  File "/Users/dsanmartim/opt/anaconda3/envs/goodman_pipeline/lib/python3.6/site-packages/goodman_pipeline-1.3.0-py3.6.egg/goodman_pipeline/core/core.py", line 1443, in get_central_wavelength
    grating_frequency = float(grating) / u.mm
ValueError: could not convert string to float:_

And here you can see a few relevant keywords from the raw data:

--> hsel *fits $I,INSTCONF,GRATING,SLIT,WAVMODE,OBSTYPE,ROI yes
0084_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0085_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0086_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0087_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0088_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0089_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0090_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0091_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0092_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0093_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0094_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0095_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0096_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0097_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0098_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0099_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0100_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0101_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0102_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0103_flat_R.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0104_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0105_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0106_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0107_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0108_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0109_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0110_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0111_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0112_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0113_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0114_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0115_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0116_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0117_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0118_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0119_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0120_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0121_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0122_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0123_flat_B.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0124_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0125_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0126_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0127_flat_V.fits	        Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0128_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0129_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0130_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0131_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0132_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0133_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0134_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0135_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0136_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0137_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0138_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0139_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0140_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0141_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0142_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0143_flat_V.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0144_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0145_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0146_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0147_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0148_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0149_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0150_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0151_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0152_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0153_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0154_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0155_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0156_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0157_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0158_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0159_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0160_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0161_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0162_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0163_flat_I.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0164_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0165_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0166_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0167_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0168_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0169_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0170_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0171_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0172_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0173_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0174_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0175_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0176_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0177_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0178_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0179_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0180_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0181_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0182_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0183_flat_Ha.fits	Red	NO_GRATING	NO_MASK	IMAGING	FLAT	"Imaging 1x1"
0185_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0186_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0187_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0188_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0189_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0190_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0191_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0192_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0193_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0194_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0195_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0196_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0197_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0198_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0199_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0200_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0201_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0202_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0203_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0204_bias.fits	Red	NO_GRATING	NO_MASK	IMAGING	BIAS	"Imaging 1x1"
0211_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0212_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0213_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0214_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0218_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0219_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0220_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0221_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0222_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0223_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0228_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0229_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0230_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0231_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0232_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0233_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0234_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0235_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0236_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0237_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0240_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0241_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0242_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0243_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0244_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0245_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0246_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0247_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0248_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0249_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0250_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0251_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0254_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0255_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0256_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0257_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0258_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"
0259_SO2019B-019.fits	Red	NO_GRATING	NO_MASK	IMAGING	OBJECT	"Imaging 1x1"

Let me know if you need additional information.

Thanks.
David.

**Comment by simontorres** [comment]
I will take a look at it today.

**Comment by simontorres** [comment]
@dsanmartim thanks for posting this issue, it is a bug indeed and though I have located the source of the problem I will no be able to provide a solution today. I'm working on getting a more robust solution so it might take one or two days. Feel free to remind me in case you don't get a response soon.

**Comment by dsanmartim** [comment]
Hi @simontorres. Thanks for the update. I'm glad this will be useful to debug the code.

**Comment by simontorres** [comment]
@dsanmartim I think I got it working properly, please re-install the code as follows.

`pip install goodman-pipeline==1.3.1.dev5`

Let me know how it goes.

**Comment by dsanmartim** [comment]
Hi Simon. It's working fine now. Thanks a lot!

**Comment by simontorres** [comment]
Excellent,
 I will close this issue now, if there is anything related to this same issue feel free to reopen it or comment.
