### ISSUE TITLE
Other day calibrations

### ISSUE THREAD

**Issue by simontorres** [soar-telescope/goodman_pipeline#51]
By parsing an argument the user could select a directory where to get calibration data. This will be useful in the case someone forgot to take calibrations one day, or maybe their calibration standards are not very strict.

**Comment by simontorres** [comment]
I could either organize the night using the calibration files in the _foreign_ folder or look for calibration in that folder when they are not found in the current one (data directory)

**Comment by b1quint** [comment]
Pinging to bring it to the top of the list.

**Comment by simontorres** [comment]
Need testing, in theory should work as long as the instrument settings are compatible.

**Comment by simontorres** [comment]
This is no longer necessary with the new version
