### ISSUE TITLE
redspec and redccd failures: ImportError: No module named _bsddb 

### ISSUE THREAD

**Issue by b1quint** [soar-telescope/goodman_pipeline#67]
`redccd` and `redspec` failed after smooth installation of the package. The traceback is shown bellow:

    ...
    File "/home/bquint/anaconda2/lib/python2.7/dbhash.py", line 7, in <module>
        import bsddb
    File "/home/bquint/anaconda2/lib/python2.7/bsddb/__init__.py", line 67, in <module>
        import _bsddb
    ImportError: No module named _bsddb 

This is caused by systems that does not have the developer version of the *Berkeley Database Libraries* for C++. To fix that, one can do the following:

1. Use apt-get, aptitude or whatever package manager you have to find out what is 
    the version of the `libdb?.?++` you have (the ?.? corresponds to the installed version).

2. Install the developer version of the installed package (e.g. libdb?.?--dev)

3. Install the `bsddb3` Python package using `pip` or your favorite method.

Voi la! The problem should be fixed!

**Comment by simontorres** [comment]
I will add this to a Wiki Page
